descriptor-schema-version: "2.7"
info:
  name: iox-aarch64-ftpserver
  description: "Alpine Linux with FTP server. Login: cisco/cisco"
  version: "1.6"
  author-link: "http://www.cisco.com"
  author-name: "Emmanuel Tychon"

app:
  cpuarch: aarch64
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    TERM: xterm
  resources:
    profile: custom
    cpu: "400"
    memory: "256"
    disk: "100"
    network:
    - interface-name: eth0
      ports:
        tcp:
          - 21
          - 20
  startup:
    rootfs: rootfs.tar
    target:
    - bash
    - /idle.sh
    workdir: /root
  type: docker
